name: KarmanaAKM CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DEBUG: false
          envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
          envkey_ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          envkey_GMAIL: ${{ secrets.GMAIL }}
          envkey_GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          envkey_APIIP_KEY: ${{ secrets.APIIP_KEY }}
          envkey_APIIP_URL: ${{ secrets.APIIP_URL }}
          envkey_HOST: ${{ secrets.HOST }}
          envkey_TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          envkey_TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASS: ${{ secrets.DB_PASS }}
          envkey_DB_SERVICE: ${{ secrets.DB_SERVICE }}
          envkey_DB_PORT: ${{ secrets.DB_PORT }}
          file_name: .env
          fail_on_empty: false
      - name: Install requirements
        run: pip install -r ./requirements/requirements.txt
      - name: Tests
        run: python manage.py test
  deploy:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Upload to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PATH }}
            git pull origin master
            source venv/bin/activate
            python manage.py makemigrations
            python manage.py migrate
            sudo systemctl restart gunicorn